### ISSUE TITLE
PlaecHolder for Auto_Respawn Task

### ISSUE THREAD

**Issue by counteracts** [iXanadu13/EnderDragon#25]
Is it possible for you to add a placeholder for auto_respawn task, if there is one already sorry & I overlooked it.

e.g

```
auto_respawn:
  task1:
    enable: true
    world_name: world_the_end
    respawn_time: 'hour:6'
```

```%ed_task1_respawntime%``` or something a long those lines as I'm trying to add a countdown for players so they're aware when the next dragon spawns.
