### ISSUE TITLE
Please add option to allow reward commands to be run even if the player is offline?

### ISSUE THREAD

**Issue by MCHalfAssed** [iXanadu13/EnderDragon#40]
For example: Can you allow "special_loot" to run the command, even if the player is offline? The Dragon report still shows the name of the player, even if they're offline. 

```
special_loot:
  # You can add more entries with DIFFERENT name according to the format.
  # If such target not exists, this option will be ignored.
  # type: exp, command 
  FirstPlace:
    enable: true
    **run if player offline: true** **< ---- suggested feature**
    type: command
    # %attacker_top_<rank>% -> the player with exactly this rank
    target: "%attacker_top_1%"
    data:
      - "crates giveKey Top_Survivor_Rewards %player% 3"

```

**Comment by iXanadu13** [comment]
https://github.com/iXanadu13/EnderDragon/blob/4f41401964d7dcd6aa19f5923f05bc825b75f31a/src/main/java/pers/xanadu/enderdragon/manager/DragonManager.java#L328-L334

Command loot is based on Server#dispatchCommand, which doesn't support offline player.
In other words, you need a command that supports offline players on its own.

**Comment by MCHalfAssed** [comment]
Hi,

Thank you for helping!! :)

The plugin (PhoenixCrates) I'm using **does** support offline players. It allows me to give virtual keys that attach to the players account, even if they are offline. 

However, EnderDragon Command loot does not run if the player is offline, after I tested. Which is why I'm asking if you can allow running the Command loot even if the player is offline.

**Comment by MCHalfAssed** [comment]
> [EnderDragon/src/main/java/pers/xanadu/enderdragon/manager/DragonManager.java](https://github.com/iXanadu13/EnderDragon/blob/4f41401964d7dcd6aa19f5923f05bc825b75f31a/src/main/java/pers/xanadu/enderdragon/manager/DragonManager.java#L328-L334)
> 
> Lines 328 to 334 in [4f41401](/iXanadu13/EnderDragon/commit/4f41401964d7dcd6aa19f5923f05bc825b75f31a)
> 
>  private static void handleCommandLoot(List<String> list, String name, String damage){ 
>      if(list == null) return; 
>      for (String cmd : list) { 
>          if(cmd.equals("")) continue; 
>          plugin.getServer().dispatchCommand(plugin.getServer().getConsoleSender(),cmd.replaceAll("%player%",name).replaceAll("%damage%",damage)); 
>      } 
>  } 
> Command loot is based on Server#dispatchCommand, which doesn't support offline player. In other words, you need a command that supports offline players on its own.

Hi,

Thank you for helping!! :)

The plugin (PhoenixCrates) I'm using does support offline players. It allows me to give virtual keys that attach to the players account, even if they are offline.

However, EnderDragon Command loot does not run if the player is offline, after I tested. Which is why I'm asking if you can allow running the Command loot even if the player is offline.

**Comment by MCHalfAssed** [comment]
**Here is a better example;**

```
special_loot:
  # You can add more entries with DIFFERENT name according to the format.
  # If such target not exists, this option will be ignored.
  # type: exp, command 
  FirstPlace:
    enable: true
    type: command
    # %attacker_top_<rank>% -> the player with exactly this rank
    target: "%attacker_top_1%"
    data:
      - "broadcast %player% did the most damage to the Dragon!"
  SecondPlace:
    enable: true
    type: command
    # %attacker_top_<rank>% -> the player with exactly this rank
    target: "%attacker_top_2%"
    data:
      - "broadcast %player% did the second most damage to the Dragon!"
```


If %attacker_top_2% is offline when the dragon dies, this command does not attempt to run:

` - "broadcast %player% did the second most damage to the Dragon!"" `
